# Generated by Django 3.2.8 on 2024-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
